vich_uploader:
    db_driver: orm

    mappings:
        photos_images:
            uri_prefix: '%photos_images%'
            upload_destination: '%kernel.project_dir%/public/images/upload_photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
